Revert commit
release-engineering/cachito pull request #473
Opened 2021-06-07 17:04 UTC by dcho5

2021-06-07 18:01 UTC, nirzari requested changes
Please use `git revert` command for reverting the commit. You can read more about it online. e.g., https://www.atlassian.com/git/tutorials/undoing-changes/git-revert

After that if you run into some merge conflicts, please resolve them manually. Make sure you don't alter the lines from the latest copy in https://github.com/dcho5/cachito/blob/master/docker/Dockerfile-workers which are not part of the commit to be reverted. For removing any dependencies added as part of the older commit, please confirm with @chmeliik if they are not being used by anything else in the module.

Finally, please use a single commit to submit your changes. Read online regarding the command `git squash`

2021-06-08 01:52 UTC, tkdchen commented
Any context about why revert the commit?

2021-06-08 07:42 UTC, chmeliik commented
@tkdchen see CLOUDBLD-3526. On that note, @dcho5 please always include the CLOUDBLD ticket in the commit message when applicable. In fact, a commit message should always have these parts:
```
Short description here

CLOUDBLD-xxxx

[optional: more detailed description]

Signed-off-by: name <email>
```
To add the signed-off-by line, you can use the `-s` option when making the commit. To add the line to an existing commit, you can use `git commit --amend -s`

2021-06-08 07:45 UTC, chmeliik commented on docker/Dockerfile-workers
> -    gettext \
I think we don't

2021-06-08 07:45 UTC, chmeliik commented on docker/Dockerfile-workers
> -    git-core \
We do need git

2021-06-08 16:16 UTC, nirzari approved these changes

2021-06-08 16:16 UTC, nirzari commented
LGTM

2021-06-09 06:27 UTC, tkdchen commented
LGTM

2021-06-09 08:55 UTC, merged